[package]
name = "seybio-task-manager"
version = "0.1.0"
edition = "2021"
description = "This lib provides a struc to manage Tasks (ie. for Todo apps)"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
